version: '3'

services:
  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    networks:
      docker_net:
        ipv4_address: 172.42.0.11
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config

  app:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: webApp
    ports:
      - "5000:5000"
    networks:
      - docker_net
    depends_on:
      - mosquitto

networks:
  docker_net:
    driver: bridge
    external: true
